import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { email, gdprConsent } = body;

    // Validate email
    if (!email || typeof email !== "string") {
      return NextResponse.json(
        { error: "L'email est requis" },
        { status: 400 }
      );
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: "Format d'email invalide" },
        { status: 400 }
      );
    }

    if (!gdprConsent) {
      return NextResponse.json(
        { error: "Le consentement RGPD est requis" },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    // Check if email already exists
    const { data: existing } = await supabase
      .from("newsletter_subscribers")
      .select("id, is_active")
      .eq("email", email.toLowerCase().trim())
      .single();

    if (existing) {
      if (existing.is_active) {
        return NextResponse.json(
          { error: "already_subscribed" },
          { status: 409 }
        );
      }
      // Re-activate a previously unsubscribed email
      const { error: reactivateError } = await supabase
        .from("newsletter_subscribers")
        .update({
          is_active: true,
          gdpr_consent: true,
          unsubscribed_at: null,
        })
        .eq("id", existing.id);

      if (reactivateError) {
        console.error("Newsletter reactivate error:", reactivateError);
        return NextResponse.json(
          { error: "Erreur lors de la réinscription" },
          { status: 500 }
        );
      }

      return NextResponse.json({ success: true });
    }

    // Insert new subscriber — unsubscribe_token is auto-generated by DB default (gen_random_uuid())
    const { error: insertError } = await supabase
      .from("newsletter_subscribers")
      .insert({
        email: email.toLowerCase().trim(),
        gdpr_consent: true,
        is_active: true,
      });

    if (insertError) {
      console.error("Newsletter insert error:", insertError);
      return NextResponse.json(
        { error: "Erreur lors de l'inscription" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Newsletter API error:", error);
    return NextResponse.json(
      { error: "Erreur interne du serveur" },
      { status: 500 }
    );
  }
}

// GET — unsubscribe via token
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get("token");

    if (!token || typeof token !== "string") {
      return NextResponse.json(
        { error: "Token de désabonnement manquant" },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    // Find subscriber by unsubscribe token
    const { data: subscriber, error: fetchError } = await supabase
      .from("newsletter_subscribers")
      .select("id, email, is_active")
      .eq("unsubscribe_token", token)
      .single();

    if (fetchError || !subscriber) {
      return NextResponse.json(
        { error: "Token invalide ou abonné introuvable" },
        { status: 404 }
      );
    }

    if (!subscriber.is_active) {
      return NextResponse.json({
        success: true,
        message: "Vous êtes déjà désabonné(e).",
        email: subscriber.email,
      });
    }

    // Deactivate subscriber
    const { error: updateError } = await supabase
      .from("newsletter_subscribers")
      .update({
        is_active: false,
        unsubscribed_at: new Date().toISOString(),
      })
      .eq("id", subscriber.id);

    if (updateError) {
      console.error("Newsletter unsubscribe error:", updateError);
      return NextResponse.json(
        { error: "Erreur lors du désabonnement" },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "Vous avez été désabonné(e) avec succès.",
      email: subscriber.email,
    });
  } catch (error) {
    console.error("Newsletter unsubscribe API error:", error);
    return NextResponse.json(
      { error: "Erreur interne du serveur" },
      { status: 500 }
    );
  }
}
